# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  # Base box
  config.vm.box = "centos6"

  # Provisioning
  config.vm.share_folder("templates", "/tmp/vagrant-puppet/templates", "templates")
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "modules"
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "nodes.pp"
    puppet.options = ["--templatedir","/tmp/vagrant-puppet/templates"]
  end

  # Server VM (Ganglia gmond + gmetad + web)
  config.vm.define :server do |server_config|
    server_config.package.name = "ganglia-server"
    server_config.vm.host_name = "ganglia-server"
    server_config.vm.forward_port 80, 9000
    server_config.vm.network :hostonly, "192.168.60.10"
    server_config.vm.customize do |vm|
      vm.memory_size = 512
    end
  end

  # Node VMs (Ganglia gmond)
  (1..9).each do |i|
    config.vm.define "node#{i}".to_sym do |server_config|
      server_config.package.name = "ganglia-node#{i}"
      server_config.vm.host_name = "ganglia-node#{i}"
      server_config.vm.network :hostonly, "192.168.60.1#{i}"
      server_config.vm.customize do |vm|
        vm.memory_size = 256
      end
    end
  end

end
